site_name: smseagle-proxy
site_description: Documentation for smseagle-proxy
repo_url: https://github.com/kartverket/smseagle-proxy
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Index:
    - 'index.md'
